### PR TITLE
chore: update `@near-js/biometric-ed25519`

### PR DESCRIPTION
**Pull request by shelegdmitriy**

### CODE REVIEW

**Comment by charleslavon** [comment]
@shelegdmitriy what UX flow can be used to check whether this update introduces a regression?

**Comment by shelegdmitriy** [comment]
Well, there is only one place where we use this module https://github.com/near/near-discovery/blob/develop/src/pages/index.tsx#L44. I'd say, we need to try to login using the fast-auth and this should be enough

**Comment by shelegdmitriy** [comment]
@DavidM-D @volovyks want to ask you guys is this is a good idea to update this package and what is the best way to test it?

**Comment by volovyks** [comment]
I never was involved in this project. @esaminu maybe you can help here.

**Comment by hcho112** [comment]
Maybe I can help answer. 
if [this](https://github.com/near/near-discovery/blob/develop/src/pages/index.tsx#L44) is only place you use this package, you don't really need to update. (But there is no harm on updating as well)

So up to maintainers really. 

To test them, based on the look, find a browser that doesn;t support passkey ([maybe from here](https://caniuse.com/passkeys)) and then see if 
```
 openToast({
            title: 'Limited Functionality',
            type: 'WARNING',
            description: 'To access all account features, try using a browser that supports passkeys',
            duration: 5000,
          });
```
This toast appears

**Pull request closed without merging**
