### PR TITLE
feat: add luma events page

### LINKED ISSUE #1252: Bring near.org/events as a components to dev.near.org/events
We need to bring events as a Native component, to not have to rely on a VM component. Besides of the current NEAR events we will also want to bring `community events`, such as those from DevHub

### PR DESCRIPTION
**Pull request by flmel**
closes #1252 
Adds Events page from multiple Luma calendars using styled React components
Adds Events form DevHubs Community Calendar
Introduces few new styled components in /components/lib/

ping @race-of-sloths

### CODE REVIEW

**Comment by flmel** [comment]
If the plan for this page is to be aggregation it makes sense to include the events from DevHub Community Calendar as well, let me know how do you guys envision them presented (ui-wise)

Leaving those for future reference

https://calendar.google.com/calendar/embed?src=c_f54ed37fd92327acdc7e4343fe40722ae5797b6c82929ba93e9f3a89c69657ab%40group.calendar.google.com&ctz=UTC

https://developers.google.com/calendar/api/v3/reference/events/list

**Comment by shelegdmitriy** [comment]
Thanks @flmel for your contribution! But It's not clear to me why do you need a whole copy of the near.org/events page here in this repo in fact that this implementation shows exact the same events (I mean the reference to luma calendars are the same)? @gagdiez what is the original goal of this PR and mentioned ticket?

**Comment by race-of-sloths** [comment]
### 🙁 This repository is not a part of the [Race of Sloths](https://race-of-sloths.com)
Please ask the maintainer to [contact us](https://github.com/NEAR-DevHub/race-of-sloths/issues/new/choose) to join the race!

<details><summary><strong>What is the Race of Sloths</strong></summary>
<p>

Race of Sloths is a friendly competition where you can participate in challenges and compete with other open-source contributors within your normal workflow

For contributors:

- Tag us inside your pull requests
- Wait for the maintainer to review and score your pull request
- Check out your position in the [Leaderboard](https://race-of-sloths.com/leaderboard)
- Keep weekly and monthly streaks to reach higher positions
- Boast your contributions with a dynamic picture of your [Profile](https://race-of-sloths.com/profile/flmel)

For maintainers:
- Score pull requests that participate in the Race of Sloths
- Engage contributors with fair scoring and fast responses so they keep their streaks
- Promote the Race to the point where the Race starts promoting you
- Grow the community of your contributors

Feel free to check [our website](https://race-of-sloths.com) for additional details!

</p>
</details>

**Comment by flmel** [comment]
Added support for google calendar events, however the page needs design/structure decisions. I've experimented with having attachments as image assets to the events.

**Comment by akorchyn** [comment]
Hey, sorry for jumping in. I have seen that you have tried to include the @race-of-sloths here.
This repo is now part of the Race of Sloths, so feel free to try it out :)

**Comment by race-of-sloths** [comment]
@flmel Thank you for your contribution! Your pull request is now a part of the [Race of Sloths](https://race-of-sloths.com)!


[<picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://badge.race-of-sloths.com/flmel?type=bot&theme=dark">
    <source media="(prefers-color-scheme: light)" srcset="https://badge.race-of-sloths.com/flmel?type=bot&theme=light">
    Shows profile picture for the author of the PR
</picture>](https://race-of-sloths.com/profile/flmel)


<details><summary>Current status: <i>waiting for scoring</i></summary>

We're waiting for maintainer to score this pull request with `@race-of-sloths score [0,1,2,3,5,8,13]` command
</details><details><summary>What is the Race of Sloths</summary>
<p>
Race of Sloths is a friendly competition where you can participate in challenges and compete with other open-source contributors within your normal workflow

For contributors:

- Tag @race-of-sloths inside your pull requests
- Wait for the maintainer to review and score your pull request
- Check out your position in the [Leaderboard](https://race-of-sloths.com/leaderboard)
- Keep weekly and monthly streaks to reach higher positions
- Boast your contributions with a dynamic picture of your [Profile](https://race-of-sloths.com/profile/flmel)

For maintainers:
- Score pull requests that participate in the Race of Sloths
- Engage contributors with fair scoring and fast responses so they keep their streaks
- Promote the Race to the point where the Race starts promoting you
- Grow the community of your contributors

Feel free to check [our website](https://race-of-sloths.com) for additional details!
</p>
</details> 

<details>
<summary>Bot commands</summary>

- For contributors
  - **Include a PR:** `@race-of-sloths include` to enter the Race with your PR
- For maintainers:
  - **Assign points:** `@race-of-sloths score [1/2/3/5/8/13]` to award points based on your assessment.
  - **Reject this PR:** `@race-of-sloths exclude` to send this PR back to the drawing board.
  - **Exclude repo:** `@race-of-sloths pause` to stop bot activity in this repo until `@race-of-sloths unpause` command is called

</details>

**Pull request closed without merging**
