### PR TITLE
Improve SEO attribution by replacing iframed wordpress content on /blog with statically generated html blog files 

### PR DESCRIPTION
**Pull request by charleslavon**
This PR replaces iframed wordpress blog content with static html files of the same content, and introduces a github submodule reference to the [static blog files](https://github.com/near/nearorg_marketing/). Along with workflow actions to support automatically updating the *.html files which are included in `public/blog`. 

Benefits of this approach: 

1.  Attributes search engine indexing results from blogs to near.org, rather than to pages.near.org
2. Allows us the ability to improve the blog UX by ensuring that link clicks open in the same window and do not lose the top level navigation options. 

Current problems with this PR: 

1. Prevent links from opening in a new tab requires a wordpress admin to change wordpress configs such that each link default to opening in the same browser window/tab
2. I would've preferred to include `public/blog` in `.gitignore`, but due to the href issue in `#1`, I've copied all `blog/*/index.html` files into `public` (that's why this PR has 2K files) and have attempted to update all links to include `target=_self`.  I'm on the fence as to whether this UX improvement is worth including all these files  (which will auto update on the next static export of wordpress content, as [per this config](https://github.com/near/nearorg_marketing/issues/1))

```
1. fix all Tags, "Blog", "Back to All Posts" links
	 public/blog/: href=/blog/>
	replace with: href=/blog target=_self />
2. fix addition a & link sources:
    public/blog/: " href=/blog/"
   replace with: "target=_self href=/blog/"

4. fix pagination links
        search public/blog/:  " href="/blog/?paged="
        replace with: "target=_self href="/blog/page/"
```

### CODE REVIEW

**Comment by calebjacob** [comment]
Thanks for taking this on @charleslavon! I'm a little hesitant to merge this due to the massive bloat of `public/blog`. Are we able to wait until the WordPress admin is able to update the links? Or maybe we can live with the links opening new tabs for the short term?

I wonder if we could somehow create a new layout (extending `DefaultLayout`) for wrapping these generated HTML pages that listens for all clicks on`<a>` elements and calls `preventDefault()` and then uses `router.push()` in certain cases to get around this link issue.

**Comment by charleslavon** [comment]
> Thanks for taking this on @charleslavon! I'm a little hesitant to merge this due to the massive bloat of `public/blog`. Are we able to wait until the WordPress admin is able to update the links? Or maybe we can live with the links opening new tabs for the short term?
> 
> I wonder if we could somehow create a new layout (extending `DefaultLayout`) for wrapping these generated HTML pages that listens for all clicks on`<a>` elements and calls `preventDefault()` and then uses `router.push()` in certain cases to get around this link issue.

hey @calebjacob I've set the majority of those links to open in the current tab via the manual search and replaces that I noted in the description. The last couple of commits have fixed the tags and pagination links.   There is no one actively maintaining this wordpress site anymore, so we can't expect anyone to update/improve those links from within WP. 

This public/blog bloat is technical debt that we can remove (and redirect to other pages) In time as this legacy content becomes older.

**Comment by charleslavon** [comment]
> @charleslavon I might be missing something, but I was doing some testing and am a bit confused.
> 
> 1. If you visit here and click on any of the blog links/posts, it still opens a new tab: https://near-discovery-git-removewpblogs-near-developer-console.vercel.app/blog
> 2. When you do visit a post, our main navigation is missing: https://near-discovery-git-removewpblogs-near-developer-console.vercel.app/blog/nears-road-to-decentralization-empowering-the-guild-community


You're right. Only the Featured Post, and Back to All Posts links will open in the current tab. The others will open in a new tab (as they currently do). So besides those two UX improvements, the primary benefit of this PR is the SEO attribution and removal of some iframed pages.

**Review by jackson-harris-iii — APPROVED** [review]
LGTM, there are a few xml feed files whose changes show up instead of simply being a diff. If there is anything to make a last review of it might be some of those files. There are quite a few of them.

**Review by calebjacob — APPROVED** [review]
Thanks for the extra context @charleslavon. Seems like this a necessary evil for now until we can somehow deprecate these pages.

**Review by shelegdmitriy — APPROVED** [review]
LGTM! Thanks for making docs at papers page as a standalone pages 🚀

**Pull request merged**
