### PR TITLE
Added NearMobileWallet in wallet-selector

### LINKED ISSUE #762: Integrate MyNEARMobile Wallet via Wallet Selector
**Is your feature request related to a problem? Please describe.**
MyNEARMobile Wallet cannot be accessed through near.org gateway

**Describe the solution you'd like**
Add MyNEARMobileWallet to Wallet selector. Example here https://near.github.io/wallet-selector/
https://github.com/near/wallet-selector/tree/main

Wallet Selector my NEAR Mobile Wallet

**Additional context**
- Download myNEARMobileWallet https://nearmobile.app/
MyNEARMobileWallet

### PR DESCRIPTION
**Pull request by erditkurteshiSQA**
Fixes #762.

Added NearMobileWallet via wallet-selector.
image

### CODE REVIEW

**Comment by erditkurteshiSQA** [comment]
We found some issues which are reported here in the comment below:
https://github.com/near/wallet-selector/pull/931#issuecomment-1782893187 

Just wanted to highlight these before proceeding with the merge

**Comment by calebjacob** [comment]
The changes look good to me, but I'll defer the approval and merging of this to @charleslavon since there are some unresolved issues with NEAR Mobile Wallet based on that issue you linked. I'm not sure if we want to hold off until those issues are resolved?

**Comment by shelegdmitriy** [comment]
Is this means we need to wait to new release of wallet-selector? It seems this issue
> We found some issues which are reported here in the comment below:
https://github.com/near/wallet-selector/pull/931#issuecomment-1782893187

was merged

**Comment by mpeterdev** [comment]
@charleslavon you may want to check in on the output of this thread before we merge: https://pagodaplatform.slack.com/archives/CT45MHDH7/p1698075035123169

**Comment by erditkurteshiSQA** [comment]
> Is this means we need to wait to new release of wallet-selector? It seems this issue
> 
> > We found some issues which are reported here in the comment below:
> > [near/wallet-selector#931 (comment)](https://github.com/near/wallet-selector/pull/931#issuecomment-1782893187)
> 
> was merged

We need to wait for a new wallet-selector release.
NearMobileWallet team should fix these issues, so the wallet-selector team can continue with the release.
These were found after merging the pr.

**Comment by charleslavon** [comment]
Thanks for the tag @mpeterdev 

Let's hold on merging this until the NearMobileWallet team responds to the branding guidelines conversation that was recently started.

**Comment by erditkurteshiSQA** [comment]
There is a new wallet-selector release and the nearMobileWallet team fixed the issue with QR code.

**Comment by charleslavon** [comment]
> Thanks for the tag @mpeterdev
> 
> Let's hold on merging this until the NearMobileWallet team responds to the branding guidelines conversation that was recently started.

I bet they are not going to respond to this. All of their branding at NEARCON used the same very similar looking Near logo.    @thisisjoshford @TiffanyGYJ any objecting to not including NearMobileWallet for now? it's not included as an option on near.social

**Comment by thisisjoshford** [comment]
> @thisisjoshford @TiffanyGYJ any objecting to not including NearMobileWallet for now? it's not included as an option on near.social

I have no objections to holding off until the branding conversation is resolved.

**Comment by erditkurteshiSQA** [comment]
@charleslavon @calebjacob 

Updated the branch with the latest changes and updated the packages with the latest version: 8.7.2 
After approval, we can merge this one.

**Comment by erditkurteshiSQA** [comment]
@charleslavon @calebjacob 

The pr is updated with the latest versions.
After approval we can merge this one.

**Comment by TiffanyGYJ** [comment]
I don't have enough context on this to comment but seems like we should be fine as long as there are clear distinctions on choices

**Review by charleslavon — APPROVED** [review]

**Comment by shelegdmitriy** [comment]
@charleslavon are we good to merge it? We are not going to wait until [this](https://github.com/near/near-discovery/pull/777#issuecomment-1808734844) is resolved, right?

**Review by shelegdmitriy — APPROVED** [review]

**Pull request merged**
