### PR TITLE
MVP of a new /addKey route which allows fastauth users to export their account to BitteWallet

### PR DESCRIPTION
**Pull request by charleslavon**
Introduces a new route `/addKey` that allows FastAuth users to initiate a transaction to add a full access public key to their account, and guides them to export the corresponding private key to [Bitte Wallet](https://wallet.bitte.ai/account/connect)

### CODE REVIEW

**Comment by charleslavon** [comment]
@shelegdmitriy @jackson-harris-iii do you mind to test this out, by logging into the preview build with a fast auth account, and provide feedback on the UX?

**Comment by shelegdmitriy** [comment]
For me, the flow itself works great! Great job @charleslavon 👏 But importing private key to Bitte wallet fails -> [loom video](https://www.loom.com/share/79684b77fa154e65999a285a0dd099ad?sid=1b1c7d1e-0859-472f-95c4-6cfd2ce110f7)

**Comment by jackson-harris-iii** [comment]
> @shelegdmitriy @jackson-harris-iii do you mind to test this out, by logging into the preview build with a fast auth account, and provide feedback on the UX?

flow works well. I think there are some UI things that could be improved, but other than that things on dev.near work well. 

I too was unable to import my key into BItte wallet.

**Review by jackson-harris-iii — APPROVED** [review]

**Comment by calebjacob** [comment]
Hey @charleslavon, I copied over and refactored your MVP code here: https://github.com/near/near-discovery/pull/1273

Does it make sense to close this PR now?

**Pull request closed without merging**
