### PR TITLE
Mint nft tool added

### PR DESCRIPTION
**Pull request by matiasbenary**
An nft can be minted with a referral contract
or if you have more advanced options, you can opt for other tools such as mintbase or paras

image

### CODE REVIEW

**Review by calebjacob — CHANGES_REQUESTED** [review]
Looks great overall! My only request would be that we remove the changes to `pnpm-lock.yaml`. We should be using `pnpm 9` to maintain consistency - the output should have `lockfileVersion: '9.0'`.

**Review by calebjacob — APPROVED** [review]
Looks good! Thanks for fixing the lock file.

**Comment by matiasbenary** [comment]
@race-of-sloths

**Comment by race-of-sloths** [comment]
### ⏰️ PR is already merged
It's too late to include us now. Include us before the merge next time!

**Pull request merged**
