### PR TITLE
add welldone wallet

### PR DESCRIPTION
**Pull request by 0xhsy**
@calebjacob The refactor/next branch seems to have already been merged, so I request to merge into the develop branch.
Thanks.

### CODE REVIEW

**Review by calebjacob — APPROVED** [review]
Looks good!

**Comment by erditkurteshiSQA** [comment]
@calebjacob 

I saw that you approved the changes but we don't have access to merge in this repository.
If you can please merge it, that would be great. Thank you!

**Comment by erditkurteshiSQA** [comment]
@0xhsy 

Can you pull the latest changes and fix the conflicts in your fork please, so it will be ready to merge? Thank you!

**Comment by 0xhsy** [comment]
> @0xhsy
> 
> Can you pull the latest changes and fix the conflicts in your fork please, so it will be ready to merge? Thank you!

Done.

**Pull request merged**
